import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readdirSync,readFileSync } from 'node:fs';
import { CLASSIC_EXP,TOTAL_EXP_TO_99,progression } from '../lib/classic-exp.ts';
// Node's native TS loader requires explicit extensions; bundle source for these tests.
import { QUESTS,questXp,finances,validateProfile,validateCannabisLog,EMPTY_PROFILE,bangkokDay } from './game-rules.bundle.mjs';
import { INSERT_QUEST,INSERT_CLEAN_QUEST,INSERT_LEVEL2_REWARD,IMPORT_LEGACY_READING } from '../lib/game-queries.ts';
const now='2026-09-30T10:00:00.000Z';
function db(){const d=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())d.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));return d;}
const total=d=>Number(d.prepare('SELECT COALESCE(SUM(xp),0) AS total FROM quest_completions WHERE user_id=?').get('owner').total);
test('all 98 Classic thresholds sum to 405,234,427 EXP',()=>{assert.equal(CLASSIC_EXP.length,98);assert.equal(TOTAL_EXP_TO_99,405234427);assert.deepEqual(CLASSIC_EXP.slice(0,10),[9,16,25,36,77,112,153,200,253,320]);});
test('every level boundary carries EXP and maxes out at level 99',()=>{let xp=0;for(let level=1;level<=98;level++){assert.equal(progression(xp).level,level);assert.equal(progression(xp).levelXp,0);assert.equal(progression(xp+CLASSIC_EXP[level-1]-1).level,level);xp+=CLASSIC_EXP[level-1];assert.equal(progression(xp).level,level+1);}assert.equal(progression(xp+100000000).level,99);assert.equal(progression(xp).levelPercent,100);assert.equal(progression(11).levelXp,2);assert.equal(progression(11).requiredXp,16);});
test('quest EXP uses server rules and higher-level tiers',()=>{assert.equal(questXp('cannabis',0),5);assert.equal(questXp('reading',0),2);assert.equal(questXp('ledger',0),1);assert.equal(questXp('cannabis',1201),19);assert.throws(()=>questXp('unknown',0));assert.equal(QUESTS.filter(q=>q.core).length,3);});
test('repeat quest claims cannot duplicate EXP; days and users are isolated',()=>{const d=db();const insert=d.prepare(INSERT_QUEST);for(let i=0;i<10;i++)insert.run('owner','2026-09-30','reading',2,now);assert.equal(total(d),2);insert.run('other','2026-09-30','reading',2,now);assert.equal(total(d),2);insert.run('owner','2026-10-01','reading',2,now);assert.equal(total(d),4);d.close();});
test('legacy readings are imported once without discarding their dates',()=>{const d=db();d.prepare('INSERT INTO habit_days (user_id,day,read_at) VALUES (?,?,?)').run('owner','2026-09-20',now);d.prepare(IMPORT_LEGACY_READING).run('owner');d.prepare(IMPORT_LEGACY_READING).run('owner');assert.equal(total(d),2);assert.equal(d.prepare('SELECT day FROM quest_completions').get().day,'2026-09-20');d.close();});
test('cannabis use blocks the clean-day award and does not affect another user',()=>{const d=db();d.prepare('INSERT INTO cannabis_logs (user_id,day,grams,trigger) VALUES (?,?,?,?)').run('owner','2026-09-30',1,'evening');assert.equal(d.prepare(INSERT_CLEAN_QUEST).run('owner','2026-09-30',5,now,'owner','2026-09-30').changes,0);assert.equal(d.prepare(INSERT_CLEAN_QUEST).run('other','2026-09-30',5,now,'other','2026-09-30').changes,1);assert.equal(total(d),0);d.close();});
test('level-2 reward requires 9 EXP and is claimed only once',()=>{const d=db();d.prepare(INSERT_QUEST).run('owner','2026-09-30','cannabis',5,now);const claim=d.prepare(INSERT_LEVEL2_REWARD);assert.equal(claim.run('owner',now,'owner').changes,0);d.prepare(INSERT_QUEST).run('owner','2026-09-30','sleep',2,now);d.prepare(INSERT_QUEST).run('owner','2026-09-30','waydidi',2,now);assert.equal(claim.run('owner',now,'owner').changes,1);assert.equal(claim.run('owner',now,'owner').changes,0);assert.equal(total(d),9);d.close();});
test('debt is monthly installment times remaining months, distinct from business profit',()=>{const p={...EMPTY_PROFILE,monthlyRevenue:5000,recurringBusinessCost:100,otherBusinessCosts:900,personalExpenses:500,debtMonthly:1000,debtMonths:12,debtPaymentsMade:2,bankBalance:250,savingsGoal:1000};const f=finances(p);assert.equal(f.debtRemaining,10000);assert.equal(f.remainingPayments,10);assert.equal(f.businessProfit,4000);assert.equal(f.cashAfterCosts,2500);assert.equal(f.savingsPercent,25);assert.equal(finances({...p,debtPaymentsMade:12}).cashAfterCosts,3500);});
test('invalid money, dates, counts, and check-ins fail before saving',()=>{assert.throws(()=>validateProfile({...EMPTY_PROFILE,monthlyRevenue:-1}));assert.throws(()=>validateProfile({...EMPTY_PROFILE,debtMonths:3,debtPaymentsMade:4}));assert.throws(()=>validateProfile({...EMPTY_PROFILE,quitDate:'2026-02-31'}));assert.throws(()=>validateProfile({...EMPTY_PROFILE,bankBalance:Infinity}));assert.throws(()=>validateCannabisLog({grams:-1,trigger:''}));assert.throws(()=>validateCannabisLog({grams:0,trigger:'a'.repeat(241)}));assert.deepEqual(validateCannabisLog({grams:0,trigger:' walk '}),{grams:0,trigger:'walk'});});
test('Bangkok midnight renews the quest day',()=>{assert.equal(bangkokDay(new Date('2026-09-30T16:59:59Z')),'2026-09-30');assert.equal(bangkokDay(new Date('2026-09-30T17:00:00Z')),'2026-10-01');});
